dist: trusty
language: generic
sudo: required
before_script:
  - sudo apt-get purge nodejs npm
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g resume-cli
script:
  - bash ./deploy.sh
